<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

<h1>Books</h1>

<hr>
author: <?=$author?>

<br>

this is list of books: <br>
<?php foreach ($books as $book) : ?>
    <?=var_dump($book)?> <br>
<?php endforeach ?>