
<div class="container">
<form method='post'  >
    <h1>Feedback</h1>
    <input type="text" class="form-control" placeholder="Author" name="author"  value="<?=$form->author ?>"/><br>
    <input type="email"  class="form-control" placeholder="Email address"  value="<?=$form->email ?>"/><br>
    <textarea name="message" class="form-control" placeholder="Your feedback"><?=$form->message ?></textarea><br>
    <button class="btn btn-lg btn-primary btn-block">Go</button>
</form>
</div>
